# Site Info
title: 11x256's blog
tagline: 'A blog about Reverse Engineering (RE)'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://11x256.github.io
#logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 11x256
  description: Malware analyst</br>Reverse engineer</br>Programmer.
  #gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
  #  linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/11x256
    # facebook:  <hide>
    twitter:   https://twitter.com/11x256
    email:     ahesham.9.3@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/'
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://11x256.github.io/'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'


# Puglins
mathjax: false # whether support mathjax
google_analytics_token: 'UA-98667589-1' # leave blank if you don't want google analytics
disqus_short_name: '11x256' # leave blank if you don't want disqus

